apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: job-board-backend
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - job-board
  endpoints:
    - port: http
      path: /health
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: job-board-frontend
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - job-board
  endpoints:
    - port: http
      path: /
      interval: 30s
