import Head from 'next/head';
import Image from 'next/image';
import Utils from './utils';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Job Board</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div>
        <h2 className='text-4xl'>Job Board</h2>
      </div>
    </div>
  );
}
